#ifndef CLEVELDEBUGPAGE_H
#define CLEVELDEBUGPAGE_H

#include "CPage.h"
#include "DataBuffer.h"

#define ID_PIBIOTCTABLE_BUTTON_PAGEDOWN 0X00AA
#define ID_PIBIOTCTABLE_BUTTON_PAGEUP   0X00AB

#define ID_CLEVELDEBUG_LABEL_EMGYBRAKE1   0X0001
//#define ID_CLEVELDEBUG_LABEL_EMGYBRAKE2   0X0002
//#define ID_CLEVELDEBUG_LABEL_EMGYBRAKE3   0X0003
//#define ID_CLEVELDEBUG_LABEL_EMGYBRAKE4   0X0004
#define ID_CLEVELDEBUG_LABEL_FASTBRAKE1   0X0005
//#define ID_CLEVELDEBUG_LABEL_FASTBRAKE2   0X0006
//#define ID_CLEVELDEBUG_LABEL_FASTBRAKE3   0X0007
//#define ID_CLEVELDEBUG_LABEL_FASTBRAKE4   0X0008
#define ID_CLEVELDEBUG_LABEL_TrBrLEVEL   0X0009
#define ID_CLEVELDEBUG_LABEL_TCUTRACTIONCOMMAND1   0X000A
#define ID_CLEVELDEBUG_LABEL_TCUTRACTIONCOMMAND2   0X000B
#define ID_CLEVELDEBUG_LABEL_TCUTRACTIONCOMMAND3   0X000C
#define ID_CLEVELDEBUG_LABEL_TCUTRACTIONCOMMAND4   0X000D

#define ID_CLEVELDEBUG_LABEL_TCUBRAKECOMMAND1   0X000E
#define ID_CLEVELDEBUG_LABEL_TCUBRAKECOMMAND2   0X000F
#define ID_CLEVELDEBUG_LABEL_TCUBRAKECOMMAND3   0X0010
#define ID_CLEVELDEBUG_LABEL_TCUBRAKECOMMAND4   0X0011
#define ID_CLEVELDEBUG_LABEL_TRACTIONPERCENT   0X0012
#define ID_CLEVELDEBUG_LABEL_BRAKEPERCENT   0X0013
#define ID_CLEVELDEBUG_LABEL_BCUTRACTIONCOMMAND1   0X0014
//#define ID_CLEVELDEBUG_LABEL_BCUTRACTIONCOMMAND2   0X002A
//#define ID_CLEVELDEBUG_LABEL_BCUTRACTIONCOMMAND3   0X002B
//#define ID_CLEVELDEBUG_LABEL_BCUTRACTIONCOMMAND4   0X002C
#define ID_CLEVELDEBUG_LABEL_BCUBRAKECOMMAND1   0X0015
//#define ID_CLEVELDEBUG_LABEL_BCUBRAKECOMMAND2   0X002D
//#define ID_CLEVELDEBUG_LABEL_BCUBRAKECOMMAND3   0X002E
//#define ID_CLEVELDEBUG_LABEL_BCUBRAKECOMMAND4   0X002F
#define ID_CLEVELDEBUG_LABEL_TCUTRACTIONCOMMANDBACK1 0X0016
#define ID_CLEVELDEBUG_LABEL_TCUTRACTIONCOMMANDBACK2 0X0017
#define ID_CLEVELDEBUG_LABEL_TCUBRAKECOMMANDBACK1 0X0018
#define ID_CLEVELDEBUG_LABEL_TCUBRAKECOMMANDBACK2 0X0019
#define ID_CLEVELDEBUG_LABEL_BCUTRACTIONCOMMANDBACK1 0X001A
#define ID_CLEVELDEBUG_LABEL_BCUTRACTIONCOMMANDBACK2 0X001B
#define ID_CLEVELDEBUG_LABEL_BCUTRACTIONCOMMANDBACK3 0X001C
#define ID_CLEVELDEBUG_LABEL_BCUTRACTIONCOMMANDBACK4 0X001D

#define ID_CLEVELDEBUG_LABEL_BCUBRAKECOMMANDBACK1 0X001E
#define ID_CLEVELDEBUG_LABEL_BCUBRAKECOMMANDBACK2 0X001F
#define ID_CLEVELDEBUG_LABEL_BCUBRAKECOMMANDBACK3 0X0020
#define ID_CLEVELDEBUG_LABEL_BCUBRAKECOMMANDBACK4 0X0021

#define ID_CLEVELDEBUG_LABEL_FASTBRAKEBACK1 0X0022
#define ID_CLEVELDEBUG_LABEL_FASTBRAKEBACK2 0X0023
#define ID_CLEVELDEBUG_LABEL_FASTBRAKEBACK3 0X0024
#define ID_CLEVELDEBUG_LABEL_FASTBRAKEBACK4 0X0025

#define ID_CLEVELDEBUG_LABEL_EMGYBRAKEBACK1   0X0026
#define ID_CLEVELDEBUG_LABEL_EMGYBRAKEBACK2   0X0027
#define ID_CLEVELDEBUG_LABEL_EMGYBRAKEBACK3   0X0028
#define ID_CLEVELDEBUG_LABEL_EMGYBRAKEBACK4   0X0029
#define ID_CLEVELDEBUG_LABEL_SPEED   0X002A
#define ID_CLEVELDEBUG_LABEL_TCUTRACTIONCOMMANDBACK3 0X002B
#define ID_CLEVELDEBUG_LABEL_TCUTRACTIONCOMMANDBACK4 0X002C
#define ID_CLEVELDEBUG_LABEL_TC1_RIOM_AI1   0X002D
#define ID_CLEVELDEBUG_LABEL_TC1_RIOM_AI2   0X002E
#define ID_CLEVELDEBUG_LABEL_TC2_RIOM_AI1   0X002F
#define ID_CLEVELDEBUG_LABEL_TC2_RIOM_AI2   0X0030
#define ID_CLEVELDEBUG_LABEL_TCUBRAKECOMMANDBACK3   0X0031
#define ID_CLEVELDEBUG_LABEL_TCUBRAKECOMMANDBACK4   0X0032
#define ID_CLEVELDEBUG_LABEL_TC1_RIOM_DUP1   0X0034
#define ID_CLEVELDEBUG_LABEL_TC1_RIOM_DUP2   0X0035
#define ID_CLEVELDEBUG_LABEL_TC2_RIOM_DUP1   0X0036
#define ID_CLEVELDEBUG_LABEL_TC2_RIOM_DUP2   0X0037

#define ID_CLEVELDEBUG_LABEL_CTBR_HBRel   0X0033

class CLevelDebugPage : public CPage
{
    DECLEAR_MESSAGE_MAP(CLevelDebugPage)
public:
    CLevelDebugPage();

protected:
    //TODO:declear call back function
    void OnUpdatePage();
    void OnShowPage();
    void OnInitPage();
private:
    void OnPageUpBtnClk();
    void OnComBtn1Clk();
    void OnComBtn6Clk();
    void UpdateCIOTCTableData();
    void SetTractionBrakeFontColor(int id, int colorVal);
    void SetTractionBrakeLabelColor(int id, int colorVal);
    void UpdateTractionLeveltest(int id);
    void UpdateTractionBrakestatus();

};

#endif // CLEVELDEBUGPAGE_H
